CANONICAL_VERTICAL_DEPTH = "Vertical Depth"
CANONICAL_FORMATION_PRESSURE = "Formation Pressure"
CANONICAL_EXCESS_PRESSURE = "Excess Pressure"

RESERVED_CANONICAL_NAMES = frozenset({
    CANONICAL_VERTICAL_DEPTH,
    CANONICAL_FORMATION_PRESSURE,
    CANONICAL_EXCESS_PRESSURE
})

USER_IMPORT_SUFFIX = "user import"